shiny:
  image:
    repository: "ghcr.io/bastienird/tunaatlas_pie_map_shiny"
    tag: "effort2026"
    pullPolicy: Always
    
  ingress:
    enabled: true
    hostname: tunaatlaspiemapshinyeffort2k26.lab.sspcloud.fr

  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"

  startupProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 60

  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 6

  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 3
    failureThreshold: 3

